name:                MPLCLI
version:             0.1.0.0
github:              "githubuser/MPLCLI"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MPLCLI#readme>

build-tools:
- alex
dependencies:
- base >= 4.7 && < 5
- parsec
- filepath
- prettyprinter
- mtl
- optics
- recursion-schemes
- pretty-show

- MPL
- MPLASM
- MPLMACH


library:
  source-dirs: src

executables:
  mpl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - MPLCLI

tests:
  MPLCLI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MPLCLI
    - QuickCheck
    - HUnit
    - hspec
    - directory
    # 'silently' is needed to listen to the output to stdout and verify it against the corrrect
    # answer
    - silently
    - parsec

benchmarks:
  MPLCLI-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - MPLCLI
    - criterion
    - template-haskell
    - parsec
    - containers
    - deepseq
    - silently
