name:                MPL2
version:             0.1.0.0
github:              "githubuser/MPL2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MPL2#readme>

dependencies:
    - base >= 4.7 && < 5
    - containers
    - unordered-containers
    - hashable
    - parsec

    - mtl
    - transformers

    - prettyprinter
    - array
    - optics
    - optics-extra
    - recursion-schemes

    - directory
    - filepath

    - raw-strings-qq
    - deepseq

library:
  source-dirs: src

executables:
  MPL2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MPL2

tests:
  MPL2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MPL2
